kind: Service
apiVersion: v1
metadata:
  name: otelcollector
  namespace: online-boutique
spec:
  type: ExternalName
  externalName: otelcollector.cil-fso.svc.cluster.local
  ports:
  - name: "1888"
    port: 1888
    targetPort: 1888
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "8889"
    port: 8889
    targetPort: 8889
  - name: "13133"
    port: 13133
    targetPort: 13133
  - name: "4317"
    port: 4317
    targetPort: 4317
  - name: "55670"
    port: 55670
    targetPort: 55670